### ISSUE TITLE
opencv4 & cv.h

### ISSUE THREAD

**Issue by opentld** [chanho-code/ORB-SLAM3forWindows#1]
Opencv/cv.h file was cancelled in opencv4, I used opencv2/opencv.hpp instead, 
but in PnPsolver.h and PnPsolver.cc, cvMat is used for svd calculation. 
Because opencv2 cancels the definitions of cvMat and cvSVD, So if opencv4 is used, how to solve these problems?
I think you are using opencv3.4.1. There should be the same problem. How did you solve it?

**Comment by opentld** [comment]
I found the solutions. Close question.

**Comment by BrsBlinder** [comment]
Hi,
Please , can you share your solution?
Have a same problem

**Comment by derGraph** [comment]
I would really like to have the solution too? Can anyone help me?
